### ISSUE TITLE
Is this able to provision virtualmin accounts ?

### ISSUE THREAD

**Issue by extremeshok** [webkitz/virtualmin_blesta#2]
Does automated account creation work ? ie. user places and pays for an order, does their virtualmin get setup ?

**Comment by jamesm66** [comment]
we are using the module and its auto provisioning, im not sure on pre-created accounts @lukesUbuntu

**Comment by lukesUbuntu** [comment]
Yes automated account creation/provisioning works fine, But due to beta i would make sure by creating a test account in blesta with credit and ordering a package with it to provision.

**Comment by lukesUbuntu** [comment]
With the new pricing on virtualmin i will put in the reseller options as well into the module.

**Comment by lukesUbuntu** [comment]
Closing issue as module can now create/cancel/suspend in virtualmin
