### ISSUE TITLE
PHP error when adding a new service

### ISSUE THREAD

**Issue by julianmatz** [webkitz/virtualmin_blesta#3]
When adding a new service in Blesta, I get the following error message:

Oh noes!

Trying to get property of non-object on line 228 in public_html/blesta/components/modules/virtualmin_blesta/virtualmin_blesta.php

**Comment by lukesUbuntu** [comment]
@julianmatz what version of blesta are you using?

**Comment by julianmatz** [comment]
Hey, Luke. It's the latest production release. 3.6.1, I think. $row =
$this->getModuleRow() returns a NULL value when trying to add a new
service.

**Comment by lukesUbuntu** [comment]
im running an older version but ill upgrade. are you running virtualmin with a ssl cert?

**Comment by julianmatz** [comment]
The problem seems to be that when adding a pacakge, it takes a very long time to load the module options.

When selecting Virtualmin as the module, the page tries to load the module options from
admin/packages/moduleoptions/

This seems to be timing out, and therefore, the module_row variable is empty when trying to add a new service, if the package is saved without module options.

It only appears to be happening with the Virtualmin module. The module options for the other modules are loading quickly. I only noticed this when I left the page open for a while and then looked at the console log in Firebug.

**Comment by julianmatz** [comment]
I'm using a self-signed certifcate on the Virtualmin server right now.

**Comment by julianmatz** [comment]
There's also a JavaScript error:

Error: TypeError: $(...).val(...) is null
Source File: /app/views/admin/default/javascript/jquery-1.8.3.min.js line 2 > eval
Line: 16

**Comment by lukesUbuntu** [comment]
okay ill upgrade my dev to the latest and check it out currently working fine on my prod environment on blesta 3.5.

**Comment by lukesUbuntu** [comment]
just upgraded, and confirmed cple of issue on fresh install with fresh virtualmin as well

**Comment by lukesUbuntu** [comment]
Should be resolved several small issues i never picked up. Has now connection checking so when you save your virtual-min it will test the connection and dump curl error log or response same for packages as well.

Will have to pull down.

**Comment by lukesUbuntu** [comment]
closing as 0a53d5e21919fa19e5471852e923bffb5174fc39 has fixed issues, confirmed with fresh blesta 3.6 & fresh virtualmin install.
