### ISSUE TITLE
Virtualmin Server Status not working properly

### ISSUE THREAD

**Issue by itangleinc** [webkitz/virtualmin_blesta#4]
Error in Server Status

http://billing.nanohosting.in/client/services/manage/6/clientTabStatus/

Parse error: syntax error, unexpected end of file in /home/nanohosting/domains/billing.nanohosting.in/public_html/components/modules/virtualmin_blesta/views/default/client_tab_status.pdt on line 153

**Comment by lukesUbuntu** [comment]
Just got your email and looking into it. Can you tell me what PHP version you are using thanks

**Comment by extremeshok** [comment]
@luke according to their website they have like 200 000 customers. I'm sure they will happily pay you as a consultant to fix the issue for them.

**Comment by itangleinc** [comment]
Hi.,

We are using the PHP Version 5.5.9

Kindly Help us

Thanks in advance

> On May 29, 2016 at 3:56 AM Luke Hardiman notifications@github.com wrote:
> 
> ```
> Just got your email and looking into it. Can you tell me what PHP version
> ```
> 
> you are using thanks
> 
> ```
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> ```
> 
> https://github.com/lukesUbuntu/virtualmin_blesta/issues/4#issuecomment-222332563
> , or mute the thread
> https://github.com/notifications/unsubscribe/AStrCq57eovPvRrEsqE11zjgvd6SidkGks5qGMEpgaJpZM4IpDnM
> .

Rathnavel B
iTANGLE Inc | Coimbatore
+91 9655592239
www.itangle.co

**Comment by itangleinc** [comment]
Hi Luke Hardiman http://webmail.itangle.co.in/appsuite/ui#

We sent some screenshots and details as per your needs 

Can you find out what is problem in Blesta-Virtualmin Module

is there any updates? possible to solve the error.?

Thanking You

> On May 29, 2016 at 3:56 AM Luke Hardiman notifications@github.com wrote:
> 
> ```
> Just got your email and looking into it. Can you tell me what PHP version
> ```
> 
> you are using thanks
> 
> ```
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> ```
> 
> https://github.com/lukesUbuntu/virtualmin_blesta/issues/4#issuecomment-222332563
> , or mute the thread
> https://github.com/notifications/unsubscribe/AStrCq57eovPvRrEsqE11zjgvd6SidkGks5qGMEpgaJpZM4IpDnM
> .

Rathnavel B
iTANGLE Inc | Coimbatore
+91 9655592239
www.itangle.co

**Comment by itangleinc** [comment]
Hi Luks Ubuntu

Very Thanks for helping to me

We replace that code.

after replacing again we get error on line 33

Error Message "Division by zero on line 33 in
/home/nanohosting/domains/billing.nanohosting.in/public_html/components/modules/virtualmin_blesta/views/default/client_tab_status.pdt"

> On June 2, 2016 at 1:43 AM Luke Hardiman notifications@github.com wrote:
> 
> ```
> Closed #4 https://github.com/lukesUbuntu/virtualmin_blesta/issues/4 via
> ```
> 
> a4dcf6c
> https://github.com/lukesUbuntu/virtualmin_blesta/commit/a4dcf6c86f7304f13326e4246801fc5cf7fbff7e
> .
> 
> ```
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> ```
> 
> https://github.com/lukesUbuntu/virtualmin_blesta/issues/4#event-678954545 , or
> mute the thread
> https://github.com/notifications/unsubscribe/AStrCtvZjJKILR8Wtszu7Ha30jpnird8ks5qHefcgaJpZM4IpDnM
> .

Rathnavel B
iTANGLE Inc | Coimbatore
+91 9655592239
www.itangle.co
