### ISSUE TITLE
Few issues found 

### ISSUE THREAD

**Issue by dformdotdk** [webkitz/virtualmin_blesta#6]
Hi

I'm really exited about blesta and your virtualmin module. I have it connected to my virtualmin server, but when I provision a new order, and activate it from admin, the order is created but I'm getting an error:

[Sat Oct 22 15:56:40.910222 2016] [fcgid:warn] [pid 8732](104)Connection reset by peer: [client _._._._:32963] mod_fcgid: error reading data from FastCGI server, referer: https://*************_.**_/********/admin/clients/editservice/1/2/

[Sat Oct 22 15:56:40.910247 2016] [core:error] [pid 8732] [client _._._._:32963] End of script output before headers: index.php, referer: https://*************_.**_/********/admin/clients/editservice/1/2/

---

Another issue - is I suspend an order from blesta admin, the Virtualmin server is still active, so it doesn't suspend it as I would expect?

---

Server groups cannot be edited or deleted after creation?

---

From client area: The tab server status gives this error: 
Division by zero on line 33 in /home/********_/public_html/**_***/components/modules/virtualmin_blesta/views/default/client_tab_status.pdt

---

From client area: Install scripts: I can't click any of the install buttons - I see the scripts, but the install button is disabled?

I really like the module, so I hope you will continue to develop it - it's great from a user perspective, making it easy to solve most common tasks related to the server.

**Comment by dformdotdk** [comment]
Another one :-)

Mail accounts: Module creates the accounts just fine, but doesn't list the accounts created.

**Comment by lukesUbuntu** [comment]
Can you tell me your current setup, php version apache version , blesta version etc. Just so i can recreate the issue. Are you using nginx? 

I will check the client provision, there is also an update to blesta which i have not checked i will go over that this weekend.

**Comment by dformdotdk** [comment]
Thanks for a fast reply :-)
I'm running PHP 5.6, Apache 2.4.18 and Blesta 3.6.2 - I'm not using Nginx
