### ISSUE TITLE
Error on adding server

### ISSUE THREAD

**Issue by dannyb2100** [webkitz/virtualmin_blesta#7]
Hey,

Thanks for creating the module first! 
But when adding a server, I am getting the following error.

> 
> Oh noes!
> 
> a:1:{s:9:"direction";a:1:{s:6:"format";s:23:"Invalid direction type.";}}

**Comment by lukesUbuntu** [comment]
Will look into it, what virtualmin version are you using?

**Comment by dannyb2100** [comment]
Hey @lukesUbuntu, sorry didn't get notified of a reply. 
I have now been moved off the project. As such cannot contribute further. 

Thank you all the same.
